"""
Pydantic models for request/response validation.
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel
from datetime import datetime


class Message(BaseModel):
    """A single message in the conversation."""
    role: str  # 'user' or 'assistant'
    content: str
    timestamp: datetime = datetime.now()


class Memory(BaseModel):
    """A retrieved memory from the database."""
    id: str
    type: str  # 'node' or 'path' or 'reasoning'
    content: str
    relevance_score: float
    metadata: Dict[str, Any] = {}


class SubQuery(BaseModel):
    """A sub-query generated by the Query Generator."""
    query: str
    purpose: str  # Why this query is being generated
    

class AgentResponse(BaseModel):
    """The agent's response to a user query."""
    response: str
    reasoning: str
    memories_used: List[Memory]
    

class MemoryUpdate(BaseModel):
    """A memory update decision from the Memory Updater."""
    action: str  # 'add', 'update', 'delete', or 'none'
    memory_type: str  # 'node', 'edge', 'reasoning'
    content: Optional[str] = None
    memory_id: Optional[str] = None
    metadata: Dict[str, Any] = {}


class QueryRequest(BaseModel):
    """Request to the /query endpoint."""
    question: str
    conversation_history: List[Message] = []


class QueryResponse(BaseModel):
    """Response from the /query endpoint."""
    response: str
    reasoning: str
    memories_used: List[Memory]
    sub_queries_generated: List[SubQuery]
    memory_updates: List[MemoryUpdate]
    conversation_id: str

