"""
Milvus Asynv API docs: https://milvus.io/docs/use-async-milvus-client-with-asyncio.md
"""

from pymilvus import AsyncMilvusClient
import os
import dotenv
from pydantic import BaseModel
from typing import Any, Literal, Optional
from openai import AsyncOpenAI as openaiAsync
import aiofiles
import json

dotenv.load_dotenv()

# define the Pydantic class for an entry in ReasoningBank collection in Milvus
class ReasoningBankEntry(BaseModel):
    """
    Pydantic model for an entry in the ReasoningBank collection.

    **Note:**
    1) `rb_id` is auto-generated primary key so we will not add it here. Insert can add duplicate entries with same primary key so we dont want to handle it ourselves.
    2) `context_sparse_vector` is auto-generated by the function we defined. We should not pass it in when creating an entry.
    """

    key_lesson_vector: list[float]  
    key_lesson: str  
    context_to_prefer_vector: list[float]
    context_to_prefer: str  
    tags: list[str]  
    link_nodes: Optional[list[str]] = None  # Optional list of linked node IDs

# pydantic class for GraphEmbeddings collection in Milvus
class GraphEmbeddingsEntry(BaseModel):
    """
    Pydantic model for an entry in the GraphEmbeddings collection.

    **Note:**
    1) `id` is auto-generated primary key so we will not add it here. Insert can add duplicate entries with same primary key so we dont want to handle it ourselves.
    2) `sparse_vector` is auto-generated by the function we defined. We should not pass it in when creating an entry.
    """

    dense_vector: list[float]  
    text: str  
    pointer_to_node: str  

class AsyncMilvus:
    def __init__(self, collection_name: Literal["graphembeddings", "reasoningbank"]):
        """
        Insert function will start the client automatically but Don't forget to close the client after use with `await client.close()`
        """
        self.uri = os.getenv("MILVUS_ENDPOINT")
        self.token = os.getenv("MILVUS_TOKEN")
        self.collection_name = collection_name

        assert self.uri is not None, "MILVUS_ENDPOINT environment variable not set"
        assert self.token is not None, "MILVUS_TOKEN environment variable not set"
        self.client = client = AsyncMilvusClient(
            uri=str(self.uri), token=str(self.token)
        )

    async def close(self):
        await self.client.close()

    async def insert_entries(
        self, entries: list[ReasoningBankEntry] | list[GraphEmbeddingsEntry]
    ):
        data = [entry.model_dump() for entry in entries]
        await self.client.insert(collection_name=self.collection_name, data=data)

class AsyncOpenAIClient:
    def __init__(self):
        """
        Don't forget to close the client after use with `await client.close()`
        """
        self.client = openaiAsync(api_key=os.getenv("OPENAI_API_KEY"))

    async def get_embedding(self, text: str) -> list[float]:
        # docs: https://platform.openai.com/docs/guides/embeddings#how-to-get-embeddings
        response = await self.client.embeddings.create(
            model="text-embedding-3-small",
            dimensions=1536,
            input=text,
        )
        return response.data[0].embedding

    async def close(self):
        await self.client.close()

class WriteDataOnFile:
    """
    Asynchronous file handler for appending and reading JSON data.
    """

    def __init__(self, filename: str, path: Optional[str] = None):
        """Initialize the file handler. Don't forget to `open` and `close` the file after write operations.
        Default stores in the same directory as this script (currently `data/milvus`)

        Args:
            filename: Name of the file (e.g., 'ReasoningBankCollectionData.json').
            path: Optional absolute path to the folder containing the file. If None, uses the folder of this script.
        """
        if path is None:
            path = os.path.dirname(os.path.abspath(__file__))  # Use absolute path of current file's directory for portability
        self.filename = os.path.join(path, filename)
        self.file_handle = None

    async def open(self):
        """
        Opens the file in `append` mode to WRITE. Sets the internal file_handle variable with the opened file. Other functions use this handle.
        """
        self.file_handle = await aiofiles.open(self.filename, mode="a")

    async def close(self):
        """Close the file handle."""
        if self.file_handle:
            await self.file_handle.close()
            self.file_handle = None

    async def write(self, data: dict[str, Any] | str):
        """Append a JSON string to the file.

        Args:
            data: JSON string or dict to append (will be serialized to JSON if dict).
        """
        try:
            if self.file_handle and isinstance(data, dict):
                data = json.dumps(data)
                await self.file_handle.write(data + "\n")  # Append newline for JSON per line
        except Exception as e:
            raise e

    async def read(self):
        """Read JSON objects from the file one by one. Assumes one JSON object per line.

        Yields:
            Parsed JSON objects (dicts) one at a time.
        """
        async with aiofiles.open(self.filename, mode="r") as f:
            async for line in f:
                line = line.strip()
                if line:
                    yield json.loads(line)
